$ErrorActionPreference='Stop'
Import-Module (Join-Path $PSScriptRoot '..\scripts\EnvironmentReadiness.psm1') -Force
Import-Module (Join-Path $PSScriptRoot '..\scripts\ExecutionGate.psm1') -Force -DisableNameChecking
function Assert([bool]$Condition,[string]$Message){if(-not $Condition){throw $Message}}
function New-TestContract([string]$Repository,[hashtable]$Environment){
  @{schema_version=2;task=@{id=('readiness-'+[guid]::NewGuid());source='test';repository=$Repository;issue=$null};goal='Environment readiness test';assignment=@{role='implementer';engine='codex'};state='READY';scope=@{bounded_context='test';allowed=@('src/**');forbidden=@('AGENTS.md','.git/**')};permissions=@{filesystem='scoped-write';git_write=$true;github_write=$true;merge=$false;production='denied'};ownership=@{task='readiness';branch=('feature/readiness-'+[guid]::NewGuid());bounded_context='test';files=@('src/**');migrations=@()};acceptance_criteria=@();verification=@{build='NOT_RUN';lint='NOT_RUN';unit='NOT_RUN';integration='NOT_APPLICABLE';e2e='NOT_APPLICABLE';guardrails='NOT_RUN';ci='NOT_RUN'};evidence=@{commit_sha=$null;changed_files=@();test_results=@();build_result=$null;playwright=$null;ci=$null;pull_request=$null};handoff=@{target_role='human';reason='test'};timestamps=@{created='2026-09-21T00:00:00Z';updated='2026-09-21T00:00:00Z'};environment=$Environment}
}
function New-Environment([object[]]$Commands=@(),[object[]]$Dependencies=@(),[object[]]$Services=@(),[object[]]$Verification=@(),[bool]$AllowPreparation=$false,[object[]]$Actions=@()){
  @{required_commands=@($Commands);dependencies=@($Dependencies);services=@($Services);verification_commands=@($Verification);preparation=@{allowed=$AllowPreparation;actions=@($Actions)}}
}
$root=Join-Path $env:TEMP ('agenthub-readiness-'+[guid]::NewGuid());New-Item -ItemType Directory $root|Out-Null;git init -q $root;git -C $root config user.email test@example.invalid;git -C $root config user.name test;New-Item -ItemType Directory (Join-Path $root 'src')|Out-Null;Set-Content (Join-Path $root 'package.json') '{}';New-Item -ItemType Directory (Join-Path $root 'deps')|Out-Null;Set-Content (Join-Path $root 'deps\ready.txt') 'ready';git -C $root add .;git -C $root commit -qm init
$ready=New-Environment -Commands @(@{name='pwsh';required=$true}) -Dependencies @(@{name='dependencies';path='deps/ready.txt';required=$true}) -Verification @(@{name='unit';file='pwsh';required=$true})
$contract=New-TestContract $root $ready;$result=Get-EnvironmentReadiness -Contract $contract -WorkingDirectory $root;Assert ($result.state -eq 'READY') 'A: ready prerequisites were not READY'
$contract.environment=New-Environment -Commands @(@{name='agenthub-missing-command';required=$true});$result=Get-EnvironmentReadiness -Contract $contract -WorkingDirectory $root;Assert ($result.state -eq 'BLOCKED') 'B: missing required executable did not block'
$prepareFile=@{id='create-dependency';file='pwsh';arguments=@('-NoProfile','-Command',"Set-Content -LiteralPath 'deps/prepared.txt' -Value ready")}
$contract.environment=New-Environment -Dependencies @(@{name='dependencies';path='deps/prepared.txt';required=$true;prepare_action='create-dependency'}) -AllowPreparation $true -Actions @($prepareFile);$result=Get-EnvironmentReadiness -Contract $contract -WorkingDirectory $root;Assert ($result.state -eq 'PREPARABLE') 'C: permitted dependency preparation was not PREPARABLE';$prepared=Invoke-EnvironmentPreparation -Contract $contract -WorkingDirectory $root -Readiness $result;Assert ($prepared.readiness.state -eq 'READY') 'D: successful preparation did not reach READY'
$failing=@{id='fail';file='pwsh';arguments=@('-NoProfile','-Command','exit 9')};$contract.environment=New-Environment -Dependencies @(@{name='dependencies';path='deps/never.txt';required=$true;prepare_action='fail'}) -AllowPreparation $true -Actions @($failing);$result=Get-EnvironmentReadiness -Contract $contract -WorkingDirectory $root;$prepared=Invoke-EnvironmentPreparation -Contract $contract -WorkingDirectory $root -Readiness $result;Assert ($prepared.readiness.state -eq 'BLOCKED' -and -not $prepared.attempted[0].succeeded) 'E: failed preparation did not block'
$contract.environment=New-Environment -Services @(@{name='app';url='http://127.0.0.1:9/health';required=$true;timeout_seconds=1});$result=Get-EnvironmentReadiness -Contract $contract -WorkingDirectory $root;Assert ($result.state -eq 'BLOCKED') 'F: unavailable service did not block'
$port=Get-Random -Minimum 40000 -Maximum 50000;$server=Join-Path $root 'service.ps1';Set-Content $server "`$listener=[Net.HttpListener]::new();`$listener.Prefixes.Add('http://127.0.0.1:$port/');`$listener.Start();`$context=`$listener.GetContext();`$context.Response.StatusCode=200;`$context.Response.Close();`$listener.Stop()"
$startService=@{id='start-service';file='pwsh';arguments=@('-NoProfile','-File','service.ps1');background=$true};$contract.environment=New-Environment -Services @(@{name='app';url="http://127.0.0.1:$port/";required=$true;timeout_seconds=3;prepare_action='start-service'}) -AllowPreparation $true -Actions @($startService);$result=Get-EnvironmentReadiness -Contract $contract -WorkingDirectory $root;Assert ($result.state -eq 'PREPARABLE') 'G: unavailable preparable service was not PREPARABLE';$prepared=Invoke-EnvironmentPreparation -Contract $contract -WorkingDirectory $root -Readiness $result;Assert ($prepared.readiness.state -eq 'READY') 'G: started service did not reach READY'
$contract.environment=New-Environment -Commands @(@{name='agenthub-optional-missing';required=$false});$result=Get-EnvironmentReadiness -Contract $contract -WorkingDirectory $root;Assert ($result.state -eq 'READY') 'J: optional prerequisite blocked readiness'
$evidence=Save-EnvironmentReadinessEvidence -WorkingDirectory $root -Initial $result -Preparation $null -Final $result;Assert ((Test-Path -LiteralPath $evidence) -and ((Get-Content -Raw $evidence|ConvertFrom-Json).final.state -eq 'READY')) 'K: readiness evidence was not persisted'
$blockedEnvironment=New-Environment -Commands @(@{name='agenthub-missing-prerequisite-tool';required=$true}) -Dependencies @(@{name='playwright-dependencies';path='node_modules';required=$true}) -Services @(@{name='test-service-app';url='http://127.0.0.1:9/health';required=$true;timeout_seconds=1}) -Verification @(@{name='playwright';file='agenthub-missing-prerequisite-tool';required=$true})
$blockedContract=New-TestContract $root $blockedEnvironment;$contractPath=Join-Path $root 'blocked-contract.json';$blockedContract|ConvertTo-Json -Depth 16|Set-Content -LiteralPath $contractPath -Encoding utf8
$hub=Join-Path $PSScriptRoot '..\scripts\agenthub.ps1';$ErrorActionPreference='Continue';$output=& pwsh -NoProfile -File $hub run $contractPath 2>&1;$exit=$LASTEXITCODE;$ErrorActionPreference='Stop';Assert ($exit -ne 0 -and ($output|Out-String) -match 'ENVIRONMENT_BLOCKED') 'H: blocked environment fixture reached execution path';$budgetPath=Get-TaskExecutionBudgetPath -Repository $root -TaskId $blockedContract.task.id;Assert (-not(Test-Path -LiteralPath $budgetPath)) 'I: blocked environment created or consumed an execution budget';$worktree=Join-Path $root ('.agenthub-worktrees\'+$blockedContract.task.id);$blockedEvidence=Join-Path $worktree '.agenthub-readiness-evidence.json';Assert ((Test-Path -LiteralPath $blockedEvidence) -and ((Get-Content -Raw $blockedEvidence|ConvertFrom-Json).final.state -eq 'BLOCKED')) 'M: blocked environment fixture did not persist pre-agent blockers'
if(Test-Path -LiteralPath $worktree){git -C $root worktree remove --force $worktree|Out-Null};Remove-Item -LiteralPath $root -Recurse -Force
Write-Output 'Environment readiness matrix A-M passed without model invocation.'
